"""changed_logic

Revision ID: bd5dc5ad8627
Revises: 052f7b817bbd
Create Date: 2026-08-17 12:55:02.773293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5dc5ad8627'
down_revision = '052f7b817bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_visit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.Column('visit_count', sa.Integer(), nullable=False),
        sa.Column('last_visit_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'note_view',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('note_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('shown_count', sa.Integer(), nullable=False),
        sa.Column('last_visit_number', sa.Integer(), nullable=True),
        sa.Column('rejected_count', sa.Integer(), nullable=False),
        sa.Column('first_shown_at', sa.DateTime(), nullable=True),
        sa.Column('last_shown_at', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['note_id'],
            ['note.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_constraint('note_type_id_fkey', 'note', type_='foreignkey')
    op.drop_table('note_type')
    op.add_column('note_response', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_response', 'created_at')
    op.create_table(
        'note_type',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='note_type_pkey'),
        sa.UniqueConstraint(
            'type_id', name='note_type_type_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    op.create_foreign_key('note_type_id_fkey', 'note', 'note_type', ['type_id'], ['type_id'])
    op.drop_table('note_view')
    op.drop_table('user_visit')
    # ### end Alembic commands ###
