"""init

Revision ID: f0cf789056cb
Revises: 
Create Date: 2026-04-12 23:16:13.886369

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f0cf789056cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'note_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'service',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'note',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type_id', sa.Integer(), nullable=False),
        sa.Column('header', sa.String(), nullable=False),
        sa.Column('info_text', sa.String(), nullable=True),
        sa.Column('rating_max', sa.Integer(), nullable=True),
        sa.Column('text', sa.String(), nullable=True),
        sa.Column('max_length', sa.Integer(), nullable=True),
        sa.Column('choice_options', sa.JSON(), nullable=True),
        sa.Column('is_multiple', sa.Boolean(), nullable=True),
        sa.Column('images', sa.JSON(), nullable=True),
        sa.Column('group_ids', sa.JSON(), nullable=False),
        sa.Column('service_ids', sa.JSON(), nullable=False),
        sa.Column('frequency', sa.Integer(), nullable=False),
        sa.Column('start_ts', sa.DateTime(), nullable=True),
        sa.Column('env_ts', sa.DateTime(), nullable=True),
        sa.Column('updated_ts', sa.DateTime(), nullable=True),
        sa.Column('is_always', sa.Boolean(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('view_count', sa.Integer(), nullable=False),
        sa.Column('rejected_count', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['type_id'],
            ['note_type.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'note_response',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('note_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('text', sa.String(), nullable=True),
        sa.Column('selected_choices', sa.JSON(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['note_id'],
            ['note.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_response')
    op.drop_table('note')
    op.drop_table('service')
    op.drop_table('note_type')
    op.drop_table('group')
    # ### end Alembic commands ###
